### ISSUE TITLE
Issue while pressing next when NUKI device is already visible in Homey

### ISSUE THREAD

**Issue by chrisboer** [jordenc/io.nuki.smartlock#1]
Stack trace:

TypeError: Cannot read property 'settings' of undefined
at sendcommand (/drivers/smartlock/driver.js:222:37)
at polling [as _onTimeout] (/drivers/smartlock/driver.js:284:4)
at Timer.listOnTimeout (timers.js:92:15)

Exit code: 1

I have smart lock firmware version 1.2.3

So it appears as connected in Homey but then it says the door lock can not be reached anymore.

Updated 

if (init == 1) {
	
		//somehow the first time polling is called immediately, there are no devices yet.
		setTimeout(polling, 5000);
		
	} else {
		setTimeout(polling, 30000);
		
		Homey.log('_______________________________________________');
		
**to** 

	if (init == 1) {
			//somehow the first time polling is called immediately, there are no devices yet.
	} else {
		setTimeout(polling, 60000);
	
		Homey.log('_______________________________________________');
		
And it works again, now the Nuki door does not disappear again and no error is sh

**Comment by jordenc** [comment]
Will update the code today, but will have to wait to go home and test it :) Thanks for mentioning.

**Comment by chrisboer** [comment]
I still have a translation issue, when I choose "Openen"  in flow action the door is not opened but just unlocked.

So I think this should be

  	"unlock": "Ontgrendelen",
  	"lock": "Vergrendelen",
  	"unlatch": "Openen",
  	"lockngo": "Automatisch vergrendelen",
  	"lockngowithunlatch": "Automatisch vergrendelen na openen"	
}

**Comment by chrisboer** [comment]
And would it be possible to add in the "flow" trigger  
if door is "unlatch" / een slot is geopened 
Because I would like to get a push message from Homey when a door is actually opened.
