### ISSUE TITLE
Flow not Triggered on Critical Battery-State

### ISSUE THREAD

**Issue by CyberSponk** [jordenc/io.nuki.smartlock#13]
Hi,

Got a Flow for the Battery-State: 
WHEN "Battery is Critical" THEN send "Push Notification".

Nuki App sent an Alert that the Battery on one NukiLOCK is low. The Flow on Homey did nothing > The Flow didn't execute.

Is this a Bug?

Greetings
Nick

Homey 1.5.13-RC11, Nuki-Smartlock-App 0.2.2

**Comment by Reemster** [comment]
I have the same flow, but with the telegram app, and that works a few days ago. Maybe there is something wrong with the Push Notification indeed..

**Comment by CyberSponk** [comment]
The Flow does two Things: Send Push and made a Log with PaperTrails. On PaperTrails didn't find an Entry. It looks like that the Flow was not executed.

How often is the Battery-State from NukiLOCK updated on Homey? Are the Values for sending BatteryAlert on the NukiApp and the Flow-Card the same?
