### ISSUE TITLE
Issue with Homey 1.0.3

### ISSUE THREAD

**Issue by chrisboer** [jordenc/io.nuki.smartlock#2]
Stack trace: SyntaxError: Unexpected token ) at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:373:25) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Module.require (module.js:353:17) at require (internal/module.js:12:17) at /homey-app/manager/drivers.js:74:27 at Array.forEach (native) at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26) Exit code: 1 Exit signal: null

**Comment by jordenc** [comment]
That should not happen with the released version in the app store, and should not happen with the current version on Github. Only the 'in-between'-version that was on Github until yesterday has this error.

**Comment by chrisboer** [comment]
Ok I had the in between version so this was the issue
