### ISSUE TITLE
feature request : battery status

### ISSUE THREAD

**Issue by chrisboer** [jordenc/io.nuki.smartlock#4]
Will it be possible to add the battery status in the Nuki app ?

**Comment by jordenc** [comment]
The Nuki bridge only reports if there is a batterywarning (true or false), not a %. 

The battery warning was working before but then I made a lot of changes, I don't think it is working now. Will soon fix that again. There is a trigger card for it already (but as said, it doesn't work currently).

**Comment by chrisboer** [comment]
This is now working in the latest release I assume

**Comment by jordenc** [comment]
It should work indeed. But my batteries aren't empty yet so I wasn't able to test :)
